import classes from "./page.module.css";

export const metadata = {
  title: 'NextJS Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 className={classes.mainHeading}>My Next.js App</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
